<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Narayana-PC" name="Test(failed)" tests="2" failures="2" timestamp="10 Oct 2016 14:51:22 GMT" time="3.636" errors="0">
  <testcase name="verifyURL" time="0.017" classname="testCasePack.Req_12345">
    <failure type="java.lang.Throwable" message="Multiple failures (2):

Failure 1 of 2:
java.lang.AssertionError: expected [Googe] but found [Google]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at utils.ErrorCollector.assertEquals(ErrorCollector.java:45)
	at utils.ErrorCollector.verifyEquals(ErrorCollector.java:98)
	at testCasePack.Req_12345.verifyURL(Req_12345.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)


Failure 2 of 2:
java.lang.AssertionError: &amp;apos;This is Message&amp;apos;------&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):

Failure 1 of 2:
java.lang.AssertionError: expected [Googe] but found [Google]
	at utils.ErrorCollector.assertEquals(ErrorCollector.java:45)
	at utils.ErrorCollector.verifyEquals(ErrorCollector.java:98)
	at testCasePack.Req_12345.verifyURL(Req_12345.java:27)


Failure 2 of 2:
java.lang.AssertionError: 'This is Message'------> expected [true] but found [false]
	at utils.ErrorCollector.assertTrue(ErrorCollector.java:29)
	at utils.ErrorCollector.verifyTrue(ErrorCollector.java:66)
	at testCasePack.Req_12345.verifyURL(Req_12345.java:28)
... Removed 58 stack frames]]>
    </failure>
  </testcase> <!-- verifyURL -->
  <testcase name="getCurrentURL" time="0.016" classname="testCasePack.Req_12345">
    <failure type="java.lang.Throwable" message="Multiple failures (2):

Failure 1 of 2:
java.lang.AssertionError: expected [URL] but found [https://www.google.co.in/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at utils.ErrorCollector.assertEquals(ErrorCollector.java:45)
	at utils.ErrorCollector.verifyEquals(ErrorCollector.java:98)
	at testCasePack.Req_12345.getCurrentURL(Req_12345.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)


Failure 2 of 2:
java.lang.AssertionError: Message----&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):

Failure 1 of 2:
java.lang.AssertionError: expected [URL] but found [https://www.google.co.in/]
	at utils.ErrorCollector.assertEquals(ErrorCollector.java:45)
	at utils.ErrorCollector.verifyEquals(ErrorCollector.java:98)
	at testCasePack.Req_12345.getCurrentURL(Req_12345.java:35)


Failure 2 of 2:
java.lang.AssertionError: Message----> expected [true] but found [false]
	at utils.ErrorCollector.assertTrue(ErrorCollector.java:29)
	at utils.ErrorCollector.verifyTrue(ErrorCollector.java:66)
	at testCasePack.Req_12345.getCurrentURL(Req_12345.java:36)
... Removed 58 stack frames]]>
    </failure>
  </testcase> <!-- getCurrentURL -->
</testsuite> <!-- Test(failed) -->
